from lxml import etree
from sys import argv, exit
from time import strftime

if len(argv) != 2:
    print('usage: {} <outfile.lua>'.format(argv[0]))
    exit(1)

with open(argv[1],'w') as outfile:
    tree = etree.parse('callbacks.xml')
    root = tree.getroot()
    pluginName = root.attrib['name']
    outfile.write('-- generated by {} on {}\n'.format(argv[0], strftime('%d/%m/%Y')))
    outfile.write('-- do not edit\n\n')
    outfile.write('local {pluginName}={{}}\n'.format(**locals()))
    for e in root.findall('command'):
        if e.tag != 'command': continue
        cmdName = e.attrib['name']
        outfile.write('{pluginName}.{cmdName}=simExt{pluginName}_{cmdName}\n'.format(**locals()))
    outfile.write('return {pluginName}\n'.format(**locals()))

